const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const context = { window: {} };
vm.createContext(context);
vm.runInContext(fs.readFileSync('港澳出入境有效天数计算器_files/calculator.js', 'utf8'), context);
const calculator = context.window.EntryExitCalculator;
const daily = ['2023-08-31', '2023-09-01', '2024-02-29', '2024-06-30', '2024-07-01', '2024-09-01'].map(date => ({ date, naturalDay: 1, validDay: 1 }));
daily[2].validDay = 0.5;
daily[2].totalDeduct = 0.5;
const academic = calculator.buildSummaryByAcademicYear(daily, 9, 6);
assert.equal(academic.length, 2);
assert.equal(academic[0].year, '2023年9月—2024年6月');
assert.equal(academic[0].naturalDays, 3);
assert.equal(academic[0].validDays, 2.5);
assert.equal(academic[0].totalDeductDays, 0.5);
assert.equal(academic[1].naturalDays, 1);
const spring = calculator.buildSummaryByAcademicYear(daily, 2, 6);
assert.equal(spring.length, 1);
assert.equal(spring[0].naturalDays, 2);
assert.equal(spring[0].year, '2024年2月—2024年6月');
const full = calculator.buildSummaryByAcademicYear(daily, 1, 12);
assert.equal(full.reduce((sum, row) => sum + row.naturalDays, 0), 6);
assert.equal(calculator.buildSummaryByAcademicYear([], 9, 6).length, 0);
assert.throws(() => calculator.buildSummaryByAcademicYear(daily, 0, 13));
assert.equal(calculator.buildSummaryByYear(daily).reduce((sum, row) => sum + row.validDays, 0), 5.5);
console.log('PASS: academic boundaries, leap day, fractional deductions, spring cohort, full year, empty data, invalid months; annual totals unchanged');
